### ISSUE TITLE
nullpo info [map-server]

### ISSUE THREAD

**Issue by vBrenth** [csnv/hercules-plugins#1] opened 2024-08-08 16:44 UTC
```\src\plugins\mimic_animations.c:133: 'src' in function `set_adelays_timer'
[Error]: --- end nullpo info ---```

To reproduce just summon alot of monster that has sonic blow skill. Let them hit you and you will get map-server error spam.

**Comment by csnv** [comment] 2024-08-08 18:06
The error was caused by `NPC_BLOODDRAIN`, a skill that uses `clif->skill_nodamage` without source.
Fixed in dadb61e9636e92a55f242bbf90d47f72eb77251d

Thanks a lot for reporting!

**Closed as completed** 2024-08-08 18:07 UTC
